# Configuration for the Flutter localization tool
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# Optional: To put generated files in lib/generated/
# output-dir: lib/generated