import 'package:flutter/material.dart';
import 'package:isar/isar.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // Import Firebase Options (generated by FlutterFire CLI)

// Import your models and the AuthGate
import 'auth_gate.dart';
import 'test_result.dart';
import 'user_model.dart';
import 'badge_model.dart' as my_models; // Added prefix
import 'leaderboard_model.dart';
import 'database_seeder.dart';
import 'isar_service.dart'; // Added import for IsarService

// HomeScreen is not directly needed as home now, AuthGate will handle it.

Future<void> main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase FIRST
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Isar - you'll likely need to do this here
  // Example: final isar = await IsarService.openDB();
  // Make sure your IsarService is correctly initialized.

  // Seed the database
  // This might need adjustment if it was Hive-dependent
  await DatabaseSeeder.seed(); 

  // If you need to debug Isar data, you can add print statements here,
  // similar to how you did for Hive, but using Isar queries.
  // For example, to get all users from Isar:
  // final isar = Isar.getInstance(); // Or however you access your Isar instance
  // if (isar != null) {
  //   final users = await isar.userProfiles.where().findAll();
  //   print('--- Contents of UserProfiles collection ---');
  //   if (users.isEmpty) {
  //     print('Collection is empty.');
  //   } else {
  //     for (var user in users) {
  //       print('User: ${user.toString()}'); // Assuming a meaningful toString()
  //     }
  //   }
  //   print('-----------------------------------------');
  // }


  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sadhak',
      theme: ThemeData(
        primarySwatch: Colors.green,
        scaffoldBackgroundColor: Colors.white,
      ),
      home: const AuthGate(),
    );
  }
}
